---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-tkmcache
  failurePolicy: Fail
  name: mtkmcache.kb.io
  rules:
  - apiGroups:
    - tkm.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tkmcaches
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-tkmcachecluster
  failurePolicy: Fail
  name: mtkmcachecluster.kb.io
  rules:
  - apiGroups:
    - tkm.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tkmcacheclusters
  sideEffects: None
