---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tkm.io
  resources:
  - tkmcacheclusters
  - tkmcaches
  - tkmnodestatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tkm.io
  resources:
  - tkmcacheclusters/finalizers
  - tkmcaches/finalizers
  - tkmnodestatuses/finalizers
  verbs:
  - update
- apiGroups:
  - tkm.io
  resources:
  - tkmcacheclusters/status
  - tkmcaches/status
  - tkmnodestatuses/status
  verbs:
  - get
  - patch
  - update
