---
apiVersion: v1
kind: Namespace
metadata:
  name: gkm-test-ns-scoped
---
apiVersion: gkm.io/v1alpha1
kind: GKMCache
metadata:
  name: vector-add-cache
  namespace: gkm-test-ns-scoped
spec:
  image: quay.io/mtahhan/01-vector-add-cache